### ISSUE TITLE
Sample does not work on Chrome Canary 93

### ISSUE THREAD

**Issue by cx20** [06wj/WebGPU-Playground#16]
The sample doesn't seem to work on Chrome Canary right now due to some breaking changes in WebGPU specs in the last few months.
The following article will be helpful for understanding the main changes.

PSA for Chromium / Dawn WebGPU API updates 2020-10-19
https://hackmd.io/@webgpu/B1UCwfgzv

PSA for Chromium / Dawn WebGPU API updates 2021-04-07
https://hackmd.io/@webgpu/HJdib9rOD

PSA for Chromium / Dawn WebGPU API updates XXXX-XX-XX
https://hackmd.io/@webgpu/BkGB45T8O

**Comment by 06wj** [comment]
Thanks.I will fix it ASAP.

**Comment by cx20** [comment]
@06wj  Thank you for fixing the samples.
I once again confirmed that those samples worked on Chrome Canary.
