### ISSUE TITLE
Cube Texture sample gives an error

### ISSUE THREAD

**Issue by cx20** [06wj/WebGPU-Playground#24]
I tried to display the following sample with `Chrome Canary 111`. 
https://06wj.github.io/WebGPU-Playground/#/Samples/CubeTexture

However, there seems to be an error in the console.

```
Tint WGSL reader failure: :20:11 error: 'final' is a reserved keyword
      var final = vec3<f32>(pos.x, pos.y, pos.z);
          ^^^^^
```

**Comment by 06wj** [comment]
Fixed it.

**Comment by cx20** [comment]
Thanks!
